---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Venn diagramm shared and unique insertions

------------------------------------------------------------------------

## Load libraries

```{r}
rm(list = ls())
library(tidyverse)
#library(VennDiagram)
library(reshape2)
#library(ggvenn)
library(ggVennDiagram)
```

## Read data

```{r}
setwd("~/sciebo/RecombinationLandscape_CRIP/02_Revision_2/BMC_Genomics_CripRecLand/New_Results/")



shared <- read.csv("~/sciebo/RecombinationLandscape_CRIP/01_Revison/Sorted_final_files/Final_Supplement/Zenodo/input-files_figures/MELT_sharedallins.csv")

subset <- read.csv("~/sciebo/RecombinationLandscape_CRIP/01_Revison/Sorted_final_files/Final_Supplement/Zenodo/input-files_figures/MELT_sharedsubsetins.csv")

unique <- read.csv("~/sciebo/RecombinationLandscape_CRIP/01_Revison/Sorted_final_files/Final_Supplement/Zenodo/input-files_figures/MELT_uniqueins.csv")

matrix <- read.csv("~/sciebo/RecombinationLandscape_CRIP/01_Revison/Sorted_final_files/Final_Supplement/Zenodo/input-files_figures/MELT_presence_absenceins.csv")
```

## Venn Diagramm

```{r}
# make it logical
matrix_df <- matrix %>%
  mutate(across(starts_with("INS"), as.logical)) 

# transpose to have populations as columns
matrix_df <- t(matrix_df)

matrix_df <- as.data.frame(matrix_df)

#matrix_df <- cbind(names = rownames(matrix_df), matrix_df)

head(matrix_df)

# define lists

sets <- list(
  MF = rownames(matrix_df)[matrix_df$MF],
  NMF = rownames(matrix_df)[matrix_df$NMF],
  MG = rownames(matrix_df)[matrix_df$MG],
  SI = rownames(matrix_df)[matrix_df$SI],
  SS = rownames(matrix_df)[matrix_df$SS]
)


# make venn diagramm
ggVennDiagram(sets)

# make it pretty
mytheme <- theme(#axis.text.x = element_text(size = 14, color = "black"),
                 #axis.text.y = element_text(size = 16, color = "black"),
                 #axis.title.y = element_text(size = 18,face = "bold", color = "black"),
                 #axis.title.x = element_text(size = 18,face = "bold", color = "black"),
                 title = element_text(size = 18, color = "black"),
                 text = element_text(size=18, color = "black"),
                 panel.background = element_blank(),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.grid.major.x = element_blank(),
                 panel.border = element_blank(),
                 plot.background = element_rect(fill="white"),
                 legend.background = element_rect(fill="white"),
                 legend.text = element_text(size = 16, color = "black"),
                 legend.position="right", 
                 axis.title.y=element_blank(),
                 axis.text.y=element_blank(),
                 axis.ticks.y=element_blank(),
                 axis.title.x=element_blank(),
                 axis.text.x=element_blank(),
                 axis.ticks.x=element_blank()) 



ggVennDiagram(sets, label_alpha = 0) +
  scale_fill_gradient(low = "mistyrose", high = "darkred") 


# Sort by similarity
# Compute Jaccard similarity matrix
library(proxy)
set_names <- names(sets)
binary_matrix <- sapply(sets, function(x) rownames(matrix_df) %in% x)
sim_matrix <- proxy::simil(t(binary_matrix), method = "Jaccard")

# Do hierarchical clustering
hc <- hclust(as.dist(1 - sim_matrix))  # 1 - sim because hclust uses distance
ordered_sets <- set_names[hc$order]

# Reorder your sets list
sets_sorted <- sets[ordered_sets]

# Plot
p <- ggVennDiagram(sets, label_percent_digit = 1, label_size = 5, set_size = 8, edge_size = .8) +
  scale_fill_gradient(low = "mistyrose", high = "darkred", name = "Count") 

p

cowplot::save_plot("C:/Users/laupe/Documents/sciebo/RecombinationLandscape_CRIP/02_Revision_2/BMC_Genomics_CripRecLand/New_Results/Venn_Diagramm_Insertions.png", p, nrow = 3, ncol = 3, base_asp = 1, dpi = 600, bg = "white", scale = 0.8)
cowplot::save_plot("C:/Users/laupe/Documents/sciebo/RecombinationLandscape_CRIP/02_Revision_2/BMC_Genomics_CripRecLand/New_Results/Venn_Diagramm_Insertions.svg", p, nrow = 3, ncol = 3, base_asp = 1, dpi = 600, bg = "white", scale = 0.65)

library(ggtext)
# Create Venn object and process data
venn <- Venn(sets)
data  <- process_data(venn)

# Compute counts + percentages
venn_data <- venn_regionlabel(data) %>%
  mutate(
    percent = count / sum(count) * 100,
    label = paste0("<b>", count, "</b><br>(", round(percent, 1), "%)")
  )

# Plot
p <- ggplot() +
  # Region fill
  geom_polygon(
    aes(X, Y, fill = count, group = id), 
    data = venn_regionedge(data)
  ) +

  # Set outlines
  geom_path(
    aes(X, Y, group = id), 
    data = venn_setedge(data), 
    show.legend = FALSE
  ) +

  # Set labels
  geom_text(
    aes(X, Y, label = name), 
    data = venn_setlabel(data),
    size = 8,
    fontface = "bold"
  ) +

  # Region labels with bold count
  geom_richtext(
    aes(X, Y, label = label), 
    data = venn_data,
    size = 5,
    label.color = NA,    # no border
    fill = alpha("white", 0.5),  # transparent background
    label.padding = unit(0.2, "lines"),
    label.r = unit(0.15, "lines")
  ) +

  coord_equal() +
  theme_void() +
  scale_fill_gradient(low = "mistyrose", high = "darkred", name = "Count") +
  theme(
        legend.title = element_text(size = 16),
    legend.text = element_text(size = 14)
  )

cowplot::save_plot("C:/Users/laupe/Documents/sciebo/RecombinationLandscape_CRIP/02_Revision_2/BMC_Genomics_CripRecLand/New_Results/Venn_Diagramm_Insertions2.png", p, nrow = 1, ncol = 1, base_asp = 1, dpi = 600, bg = "white", scale = 2.1)
cowplot::save_plot("C:/Users/laupe/Documents/sciebo/RecombinationLandscape_CRIP/02_Revision_2/BMC_Genomics_CripRecLand/New_Results/Venn_Diagramm_Insertions2.svg", p, nrow = 1, ncol = 1, base_asp = 1, dpi = 600, bg = "white", scale = 2.1)

```


#' Complex Upset Plot
```{r}
library(ComplexUpset)

# Let's add a column for INS name (if needed)
matrix_df$INS <- rownames(matrix_df)

# Bring INS to the first column
upset_data <- matrix_df[, c("INS", setdiff(names(matrix_df), "INS"))]

# Plot UpSet
upset(upset_data, intersect = c("MF", "NMF", "MG", "SI", "SS"))

# Sort by similarity
p <- upset(upset_data, intersect = c("MF", "NMF", "MG", "SI", "SS"),
      sort_intersections_by = "cardinality", 
  min_size = 1,
  width_ratio = 0.2
) +
  theme_minimal(base_size = 14) +  # cleaner font
  theme(
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid.major.y = element_line(color = "gray80", linetype = "dotted")
  ) 

cowplot::save_plot("C:/Users/laupe/Documents/sciebo/RecombinationLandscape_CRIP/02_Revision_2/BMC_Genomics_CripRecLand/New_Results/Upset_Plot_Insertions.png", p, nrow = 2, ncol = 2, base_asp = 1.6, dpi = 600, bg = "white", scale = 0.7)
cowplot::save_plot("C:/Users/laupe/Documents/sciebo/RecombinationLandscape_CRIP/02_Revision_2/BMC_Genomics_CripRecLand/New_Results/Upset_Plot_Insertions.svg", p, nrow = 2, ncol = 2, base_asp = 1.6, dpi = 600, bg = "white", scale = 0.7)

```