---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Recombination Hot- and Coldspots

------------------------------------------------------------------------

## Prepare environment

```{r}
## Clean environment
rm(list = ls())
#invisible(lapply(paste0('package:', names(sessionInfo()$otherPkgs)), detach, character.only=TRUE, unload=TRUE))

# Load libraries
library(tidyverse)
#library(dplyr)
#library(scales)
#library(ggplot2)
library(patchwork)
library(cowplot)
#library(grid)
#library(gridExtra)
library(zoo)

# Set directory
setwd("~/sciebo/RecombinationLandscape_CRIP/02_Revision_2/BMC_Genomics_CripRecLand/New_Results/")
getwd()

```

## Load recombination data files

```{r}
#-------------------------------------------------------------------
# Load data
#-------------------------------------------------------------------
ind <- c("MF1", "MF2", "MF3", "MF4", "MG2", "MG3", "MG4", "MG5", "NMF1", "NMF2", "NMF3", "NMF4", 
         "SI1", "SI2", "SI3", "SI4", "SS1", "SS2", "SS3", "SS4")
chr <- c("Chr1", "Chr2", "Chr3", "Chr4")

common_path = "~/sciebo/RecombinationLandscape_CRIP/01_Revison/Sorted_final_files/Final_Supplement/Zenodo/iSMC/"

# Chr1
files_to_read_1 = list.files(
  path = common_path,        # directory to search within
  pattern = "*Chr1_ismc.rho.10kb.bedgraph", # regex pattern, some explanation below
  recursive = TRUE,          # search subdirectories
  full.names = TRUE          # return the full path
)
data_lst_1 = lapply(files_to_read_1, read.table, header = TRUE)  # read all the matching files

# Chr2
files_to_read_2 = list.files(
  path = common_path,        # directory to search within
  pattern = "*Chr2_ismc.rho.10kb.bedgraph", # regex pattern, some explanation below
  recursive = TRUE,          # search subdirectories
  full.names = TRUE          # return the full path
)
data_lst_2 = lapply(files_to_read_2, read.table, header = TRUE)  # read all the matching files

# Chr3
files_to_read_3 = list.files(
  path = common_path,        # directory to search within
  pattern = "*Chr3_ismc.rho.10kb.bedgraph", # regex pattern, some explanation below
  recursive = TRUE,          # search subdirectories
  full.names = TRUE          # return the full path
)
data_lst_3 = lapply(files_to_read_3, read.table, header = TRUE)  # read all the matching files

# Chr4
files_to_read_4 = list.files(
  path = common_path,        # directory to search within
  pattern = "*Chr4_ismc.rho.10kb.bedgraph", # regex pattern, some explanation below
  recursive = TRUE,          # search subdirectories
  full.names = TRUE,          # return the full path
)
data_lst_4 = lapply(files_to_read_4, read.table, header = TRUE)  # read all the matching files

#-------------------------------------------------------------------
# Rename columns
#-------------------------------------------------------------------
# Rename data list names
names(data_lst_1) <- ind
names(data_lst_2) <- ind
names(data_lst_3) <- ind
names(data_lst_4) <- ind

# Check if renaming worked fine
#Make empty list, otherwise loop won't work
check_rename <- list()

for (i in 1:20){
  check_rename[i] <- identical(names(data_lst_1[i]), colnames(data_lst_1[[i]][4]))
}
check_rename


for (i in 1:20){
  check_rename[i] <- identical(names(data_lst_2[i]), colnames(data_lst_2[[i]][4]))
}
check_rename

for (i in 1:20){
  check_rename[i] <- identical(names(data_lst_3[i]), colnames(data_lst_3[[i]][4]))
}
check_rename

for (i in 1:20){
  check_rename[i] <- identical(names(data_lst_4[i]), colnames(data_lst_4[[i]][4]))
}
check_rename

# Rename columns in every data frame
# https://stackoverflow.com/questions/28648513/changing-column-names-in-a-list-of-data-frames-in-r
new_colnames <- c("chromosome", "start", "end", "rho")

data_lst_1 <- lapply(data_lst_1, rename_with, ~ new_colnames)
data_lst_2 <- lapply(data_lst_2, rename_with, ~ new_colnames)
data_lst_3 <- lapply(data_lst_3, rename_with, ~ new_colnames)
data_lst_4 <- lapply(data_lst_4, rename_with, ~ new_colnames)

# Change names in chromosome column to the correct chromosome
for (i in 1:20){
  data_lst_1[[i]][1] <- "Chr1"
}

for (i in 1:20){
  data_lst_2[[i]][1] <- "Chr2"
}

for (i in 1:20){
  data_lst_3[[i]][1] <- "Chr3"
}

for (i in 1:20){
  data_lst_4[[i]][1] <- "Chr4"
}

# Add column with individual name
for (i in 1:20){
  data_lst_1[[i]]$individual <- names(data_lst_1[i])
}

for (i in 1:20){
  data_lst_2[[i]]$individual <- names(data_lst_2[i])
}

for (i in 1:20){
  data_lst_3[[i]]$individual <- names(data_lst_3[i])
}

for (i in 1:20){
  data_lst_4[[i]]$individual <- names(data_lst_4[i])
}

# Merge dataframes into one big dataframe (df1 = chr1, df2 = chr2, ...)
df1 <- bind_rows(data_lst_1)
df2 <- bind_rows(data_lst_2)
df3 <- bind_rows(data_lst_3)
df4 <- bind_rows(data_lst_4)

df <-  rbind(df1,df2,df3,df4)

# Remove incomplete windows
df <- df %>%
  mutate(wnd_size = end-start)

unique(df$wnd_size) # window size should be only 10,000

window_size = 10e3

df <- df %>% 
  filter(wnd_size == window_size)

# also for the separate df
df1 <- df1 %>%
  mutate(wnd_size = end-start) %>% 
  filter(wnd_size == window_size)

df2 <- df2 %>%
  mutate(wnd_size = end-start) %>% 
  filter(wnd_size == window_size)

df3 <- df3 %>%
  mutate(wnd_size = end-start) %>% 
  filter(wnd_size == window_size)

df4 <- df4 %>%
  mutate(wnd_size = end-start) %>% 
  filter(wnd_size == window_size)

unique(df4$wnd_size)

#----------------------------------------------------------
# Calculate mean and confidence interval
## Chr1
head(df1)
mf_mean1 <- df1 %>% 
  filter(individual == "MF1" | individual == "MF2" | 
           individual == "MF3" | individual == "MF4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))

head(mf_mean1)

mg_mean1 <- df1 %>% 
  filter(individual == "MG2" | individual == "MG3" | 
           individual == "MG4" | individual == "MG5") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(mg_mean1)

nmf_mean1 <- df1 %>% 
  filter(individual == "NMF1" | individual == "NMF2" | 
           individual == "NMF3" | individual == "NMF4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(nmf_mean1)

si_mean1 <- df1 %>% 
  filter(individual == "SI1" | individual == "SI2" | 
           individual == "SI3" | individual == "SI4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(si_mean1)

ss_mean1 <- df1 %>% 
  filter(individual == "SS1" | individual == "SS2" | 
           individual == "SS3" | individual == "SS4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(ss_mean1)

## Chr2
head(df2)
mf_mean2 <- df2 %>% 
  filter(individual == "MF1" | individual == "MF2" | 
           individual == "MF3" | individual == "MF4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(mf_mean2)

mg_mean2 <- df2 %>% 
  filter(individual == "MG2" | individual == "MG3" | 
           individual == "MG4" | individual == "MG5") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(mg_mean2)

nmf_mean2 <- df2 %>% 
  filter(individual == "NMF1" | individual == "NMF2" | 
           individual == "NMF3" | individual == "NMF4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(nmf_mean2)

si_mean2 <- df2 %>% 
  filter(individual == "SI1" | individual == "SI2" | 
           individual == "SI3" | individual == "SI4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(si_mean2)

ss_mean2 <- df2 %>% 
  filter(individual == "SS1" | individual == "SS2" | 
           individual == "SS3" | individual == "SS4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(ss_mean2)

## Chr3
head(df3)
mf_mean3 <- df3 %>% 
  filter(individual == "MF1" | individual == "MF2" | 
           individual == "MF3" | individual == "MF4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(mf_mean3)

mg_mean3 <- df3 %>% 
  filter(individual == "MG2" | individual == "MG3" | 
           individual == "MG4" | individual == "MG5") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(mg_mean3)

nmf_mean3 <- df3 %>% 
  filter(individual == "NMF1" | individual == "NMF2" | 
           individual == "NMF3" | individual == "NMF4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(nmf_mean3)

si_mean3 <- df3 %>% 
  filter(individual == "SI1" | individual == "SI2" | 
           individual == "SI3" | individual == "SI4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(si_mean3)

ss_mean3 <- df3 %>% 
  filter(individual == "SS1" | individual == "SS2" | 
           individual == "SS3" | individual == "SS4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(ss_mean3)

## Chr4
head(df4)
mf_mean4 <- df4 %>% 
  filter(individual == "MF1" | individual == "MF2" | 
           individual == "MF3" | individual == "MF4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(mf_mean4)

mg_mean4 <- df4 %>% 
  filter(individual == "MG2" | individual == "MG3" | 
           individual == "MG4" | individual == "MG5") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(mg_mean4)

nmf_mean4 <- df4 %>% 
  filter(individual == "NMF1" | individual == "NMF2" | 
           individual == "NMF3" | individual == "NMF4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(nmf_mean4)

si_mean4 <- df4 %>% 
  filter(individual == "SI1" | individual == "SI2" | 
           individual == "SI3" | individual == "SI4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(si_mean4)

ss_mean4 <- df4 %>% 
  filter(individual == "SS1" | individual == "SS2" | 
           individual == "SS3" | individual == "SS4") %>%
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))
head(ss_mean4)
#----------------------------------------------------------
```

## Define themes

```{r}
pop <-  c("MF", 
          "NMF", 
          "MG", 
          "SI", 
          "SS")

#my_palette <- c("#355BA4",
#                "#8f4e8a",
#                "#287f97",
#                 "#b26712",
#                "#AB3232")

my_palette <- c("#4C83EB",
                "#CD70C6",
                "#3AB6D8",
                "#FF941A",
                "#AB3232")

# Define theme
mytheme <- theme(axis.text.x = element_text(size = 14, color = "black"),
                 axis.text.y = element_text(size = 14, color = "black"),
                 axis.title.y = element_text(size = 14,face = "bold", color = "black"),
                 axis.title.x = element_text(size = 14,face = "bold", color = "black"),
                 title = element_text(size = 12, color = "black"),
                 panel.background = element_rect(fill="white"),
                 panel.grid.major = element_line("lightgrey"),
                 panel.grid.minor = element_line("white"),
                 panel.border = element_rect("black", fill = NA),
                 plot.background = element_rect(fill="white"),
                 legend.background = element_rect(fill="white"),
                 legend.position="bottom")
```

## Define hot- and colgdspots

Mean + 2xSD = hot

Mean - 2x SD = cold

for each chromosome

```{r}
# Calculate mean, SD and confidence interval per chromosome
head(df)

# calculate global mean and sd per chromosome
rho_chr_mean <- df %>%
  group_by(chromosome) %>% 
  summarise(N_global = n(),
            mean_rho_global = mean(rho),
            sd.rho_global = sd(rho),
            SE.low_global = mean_rho_global - (sd(rho)/sqrt(N_global)),
            SE.high_global = mean_rho_global + (sd(rho)/sqrt(N_global)))
  

# now define hotspots
# mean per population per postition
df_mean <- df %>% 
  group_by(chromosome, start, end)  %>% 
  summarise(N = n(),
            mean_rho = mean(rho),
            sd.rho = sd(rho),
            SE.low = mean_rho - (sd(rho)/sqrt(N)),
            SE.high = mean_rho + (sd(rho)/sqrt(N)))

# join global mean with mean per populations
df_mean_joined <- df_mean %>%
  left_join(rho_chr_mean, by = "chromosome") %>% 
  mutate(spot = case_when(
    mean_rho >= (mean_rho_global + 2*sd.rho_global) ~ "hotspot", 
    mean_rho <= (mean_rho_global - 2*sd.rho_global) ~ "coldspot",
    TRUE ~ "expected_range")
    )
write.csv(df_mean_joined, "chromosome_mean_rho_and_global_mean_with_hotspots_10kb.csv")

unique(df_mean_joined$spot)
count(df_mean_joined, spot)
# no hotspot found

# join global mean with full data set
df_joined <- df %>%
  left_join(rho_chr_mean, by = "chromosome") %>% 
  mutate(spot = case_when(
    rho >= (mean_rho_global + 2*sd.rho_global) ~ "hotspot", 
    rho <= (mean_rho_global - 2*sd.rho_global) ~ "coldspot",
    TRUE ~ "expected_range")
    )

unique(df_joined$spot)
count(df_joined, spot)



# plot it
ggplot(df_joined, aes(x = rho)) +
  geom_histogram(bins = 50, fill = "grey") +
  geom_vline(aes(xintercept = mean_rho_global +  2*sd.rho_global), color = "red") +
  geom_vline(aes(xintercept = mean_rho_global -  2*sd.rho_global), color = "blue") +  facet_wrap(~chromosome)
```

no coldspots found

## Plot heatmap

### Load chromosome info

```{r}
#read-in chromosome and scaffold data 
chr.data <- read.table("~/sciebo/RecombinationLandscape_CRIP/01_Revison/Sorted_final_files/Final_Supplement/Zenodo/input-files_figures/crip4.0_genome_chr_length.csv", sep = ";", header = TRUE)

class(chr.data)

head(chr.data)

chr.data <- chr.data %>% 
  dplyr::rename("chr" = "Name",
         "chr_start" = "Start",
         "chr_end" = "End")

str(chr.data)
chr.data

# define chromosomes of interest
target <- c("Chr1", "Chr2", "Chr3", "Chr4")

# modify chromosome data frame to filter and start at 0 and get end in Mb
chromosomes <- chr.data %>%
  filter(chr %in% target) %>%
  select(chr, chr_end) %>%
  mutate(chr_start = 0) %>%
  mutate(chr_end = chr_end/1e6)

chromosomes


# add centromere ranges
# Read in centromere ranges
cenrange <- read.csv("~/sciebo/RecombinationLandscape_CRIP/01_Revison/NewResults/CentromereRange.csv", sep = ",", header = TRUE)
head(cenrange)

cenrange <- cenrange %>%
  mutate(
    censtart = censtart/1e6,
    cenend = cenend/1e6
  ) %>%
  rename("chr" = "Chromosome")

```

## Load Cla-element data

```{r}
cla_colnames = c("chr", "start", "end", "repeatname")

cla <- read.table("/Users/laupe/Downloads/Cla1.master_AllPop.bedgraph" , header = FALSE, na.string = "NA", sep = "\t", col.names = cla_colnames)
#cla <- read.table("/home/alle/recombination-map/MELT/MELT-run2/Cla1/AllPop/2-GroupAnalysis//Cla1.master_AllPop.bedgraph" , header = FALSE, na.string = "NA", sep = "\t", col.names = cla_colnames)

cla <- cla %>%
  mutate(length = end - start) %>%
  filter(chr %in% c("Chr1", "Chr2", "Chr3", "Chr4"))

cla$chr <- as.factor(cla$chr)

```

### Plot it

```{r}
df_mean <-  df_mean %>%
  rename(chr = chromosome)

hotspots_data <- df_joined %>%
  filter(spot == "hotspot") %>%
  rename(chr = chromosome)

hotspots <- hotspots_data %>%
  group_by(chr, start, end) %>%
  summarise(
    n_ind = n_distinct(individual),
    individuals = paste(unique(individual), collapse = ",")
  ) %>%
  ungroup

write.csv(df_joined, "all_rho_and_global_mean_with_hotspots_10kb.csv")
write.csv(hotspots, "hotspots_rho_10kb.csv")
write.csv(hotspots_data, "hotspots_rho_10kb.csv")

mytheme <- theme(axis.text.x = element_text(size = 14, color = "black"),
                 #axis.text.y = element_text(size = 16, color = "black"),
                 #axis.title.y = element_text(size = 18,face = "bold", color = "black"),
                 axis.title.x = element_text(size = 18,face = "bold", color = "black"),
                 title = element_text(size = 17, color = "black"),
                 text = element_text(size=17, color = "black"),
                 panel.background = element_rect(fill="white"),
                 panel.grid.major = element_line("white"),
                 panel.grid.minor = element_line("white"),
                 panel.grid.major.x = element_line("lightgrey", linetype = 3),
                 panel.border = element_rect("black", fill = NA),
                 plot.background = element_rect(fill="white"),
                 legend.background = element_rect(fill="white"),
                 legend.position="bottom", 
                 axis.title.y=element_blank(),
                 axis.text.y=element_blank(),
                 axis.ticks.y=element_blank()) 

p <- ggplot(chromosomes) +
  geom_rect(mapping = aes(xmin = chr_start, xmax = chr_end, ymin = 0, ymax = 1), fill = "white") +
  # centromere ranges
  geom_segment(data = cenrange,
             aes(x = censtart, xend = cenend, y = 1.05, yend = 1.05),
             color = "grey25", size = 1.5) +
  # mark hotspots
  #geom_point(data = cla, aes(x = start / 1e6, y = -0.05), color = "black", size = 1.5) +
  geom_rect(data = hotspots,
          aes(xmin = start / 10^6, xmax = end / 10^6, ymin = -0.25, ymax = -0.05),
          color = "#E94742", alpha = 0.002) +
  # add cla-elements
  geom_rect(data = cla,
          aes(xmin = start / 10^6, xmax = end / 10^6, ymin = -0.50, ymax = -0.25),
          color = "darkred", alpha = 0.002) +
  # add mean recombination
  geom_rect(data = df_mean, 
            mapping = aes(xmin = start / 10^6, xmax = end / 10^6, ymin = 0, ymax = 1 ,  color = mean_rho)) +
  mytheme + 
  labs(x = "Position (Mb)") +
  scale_x_continuous(labels = scales::comma, n.breaks = 6, position = "top") +
  scale_y_continuous(limits = c(-0.50, 1.05)) +
  #scale_color_gradient2(low = muted("blue"), mid = "orange", high = muted("red"), midpoint = 3, trans = "sqrt") +
  scale_color_viridis_c(option = "F", direction = 1, name = "Mean \u03c1") +
    
  facet_grid(chr ~ .) +
  theme(axis.text.x = element_text(size = 14, color = "black", angle = 0),
        legend.position="bottom",
        legend.key.width = unit(1, "cm"))  # Adjusting text size and angle 

print(p)

cowplot::save_plot("~/sciebo/RecombinationLandscape_CRIP/02_Revision_2/BMC_Genomics_CripRecLand/New_Results/Heatmap_rho_10kb_centromere_cla.svg", p,nrow = 2, ncol = 6, base_asp = .9, dpi = 600, bg = "white", scale = 0.7)
cowplot::save_plot("~/sciebo/RecombinationLandscape_CRIP/02_Revision_2/BMC_Genomics_CripRecLand/New_Results/Heatmap_rho_10kb_centromere_cla.png", p, nrow = 2, ncol = 6, base_asp = .9, dpi = 600, bg = "white", scale = 0.7)

```
